### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.text.Text on Fabric 1.20.1

### ISSUE THREAD

**Issue by burdoto** [Mineaurion/AurionChat#25]
Hello, I am encountering an issue using this plugin on a Fabric 1.20.1 server.
Looking at the files, you seem to target this specific version; however I couldn't get it to work even by creating a custom build.

Here's the full log: https://hastebin.com/share/qicaluheva.sql

**Comment by Yann151924** [comment]
Hi,
With the latest version normally it work with the 1.20.1 fabric, if not i can release a new one.
If you want to custom build you need to change this : https://github.com/Mineaurion/Aurionchat/blob/master/gradle.properties#L3 with like "1.0.0" forge and fabric don't like the "SNAPSHOT" word in the version

**Comment by burdoto** [comment]
i didnt have issues with the version name, but thats a good note thanks

however, it will not load for some reason.
similarly, the bukkit version also doesnt initialize (inside an arclight instance):
https://hastebin.com/share/efavocuhoq.markdown
rabbitmq url was checked multiple times, that one is alright

**Comment by Gaetann18** [comment]
did you correctly specify the port in the rabbit mq url?

**Comment by burdoto** [comment]
yes, it was checked several times and uses the correct port, ip, vhost, username and password

**Comment by Gaetann18** [comment]
can you attach your configuration file to me?

**Comment by burdoto** [comment]
https://pastebin.com/XZjXrtPL

**Comment by Gaetann18** [comment]
rabbitmq:
  uri: "amqp://minecraft:youpassword@yourip:5672"
remove /minecraft

**Comment by burdoto** [comment]
rabbitmq docs state that [the URI should be terminated with a segment that defines the Vhost to be used](https://www.rabbitmq.com/uri-spec.html), but i will try that in a minute

**Comment by Gaetann18** [comment]
Of memory in the plugin code it will automatically increment

**Comment by burdoto** [comment]
has a similar result without the vhost parameter: https://pastebin.com/aW5RPenj

**Comment by Gaetann18** [comment]
use this template and everything should work

``` 
rabbitmq:
  uri: "amqp://youruser:yourpassword@yourip:5672"
  servername: "youservername1" #Must be unique beetwen all of our servers 


options:
  spy: false
  automessage: false
  sound: "ENTITY_EXPERIENCE_ORB_PICKUP"

channels:
   youservername1:
     format: "[&a PREFIX &f] {prefix}{display_name} : &f{message}"
     alias: "youralias"
   youservername2:
     format: "[&6PREFIX &f] {prefix}{display_name} : &f{message}"
     alias: "yoursecondalias"
```
